# Generated by Django 4.2.3 on 2023-07-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0002_alter_usertype_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('citizenship_image', models.ImageField(upload_to='static/image')),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(max_length=255, upload_to='static/')),
            ],
        ),
    ]
