# Generated by Django 4.2.1 on 2023-07-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0003_serviceprovidermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovidermodel',
            name='type_of_service',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
