# Generated by Django 4.2.1 on 2023-07-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0005_alter_serviceprovidermodel_type_of_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovidermodel',
            name='citizenship_image',
            field=models.ImageField(upload_to='./documents'),
        ),
        migrations.AlterField(
            model_name='serviceprovidermodel',
            name='cv',
            field=models.FileField(max_length=255, upload_to='./documents'),
        ),
    ]
