# Generated by Django 4.2.1 on 2023-07-20 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackapp', '0011_serviceprovidermodel_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequestsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackapp.serviceprovidermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
